views/admin/users.erb, views/home.erb
The change made per NU IT Support Issue 322180 (user page font size change).
=> Update markup so old small tags display correctly

routes/tools.rb, views/new_member_signup.erb
My Support Request: https://mysupport.unl.edu/MRcgi/MRlogin.pl?DL=322644DA14
Additional Info from stakeholder:
If the max hours ends up to be multiple days then yes that is ok.  The limitation of reservations to only open hours is the issue.  Simple solution is to allow reservations to exceed  both open hours and for multiple days.  I can then control how many hours reservations on each piece of equipment can be made on the specific equipment page, and exceed open studio hours if needed.
Also includes form fix to correct broken layout: https://mysupport.unl.edu/MRcgi/MRlogin.pl?DL=323571DA14
=> Fix tool reservation issue and broken form

routes/tools.rb, views/reserve.erb
=> Bug fixes so reserve/edit display correctly when a reservation spans multiple days

views/fixed.erb
WIP until WDN version 5.3 is available.
=> Support WDN version 5.3

views/admin/events.erb
To ignore whitespace changes: https://github.com/unl/reservations/pull/57/files?w=1
These changes are dependent on WDN rollout with support for DCF pagination.
=> WIP: Implement DCF Pagination

views/admin/events.erb, views/calendar.erb, views/event_listing_table.erb
Let users with the manage events permission be able to view and edit private events
=> Changed permissions from super_user to mange events

models/user.rb, routes/vehicles.rb
Vehicle update emails have not been sending. This seems like the reason why.
=> Save vehicle data before trying to send email

routes/vehicles.rb
Fix issue where users are not being attached to car
=> Save vehicle after user is assigned to it

routes/admin/users.rb, views/admin/modify_expirations.erb
Changes input type to a number to allow positive and negative numbers
Added validation on backend to check if value is numeric
=> Allow negative modify

Gemfile.lock, app.rb, models/material_price.rb, models/resource.rb, pricing.sql, routes/admin/alerts.rb, routes/admin/events.rb, routes/admin/material_prices.rb, routes/admin/tools.rb, routes/admin/users.rb, routes/alert_center.rb, routes/pricing.rb, routes/tools.rb, routes/training_documents.rb, views/admin/material_prices.erb, views/navigation.erb, views/pricing.erb, views/sop_training_document.erb, views/tips_and_tricks_training_document.erb, views/training_documents.erb, views/workshops_training_document.erb
- Update drupal pages to point to new D10 site
- Moved Material prices away from D10
- Added a new table in the database for storing material pricing data
- Added an Admin page for editing
- The data is formatted on the pricing page 
- Updated libv8 to work on M1 macs
- Updated misc. sorting due to actually use strings
=> Drupal page update

models/user.rb
There was a CRON error for a missing email
=> Add check for missing email

data/updates/0004_optional_hrc_parking.sql, models/event.rb, views/admin/new_event.erb, views/new_member_signup_hrc.erb
Added option for HRC events to have parking be optional
=> Optional HRC Parking

routes/admin/events.rb
Removed logic for event_type_allow_signup_deletions and just return true
=> Added delete signup checkbox for all event types

routes/admin/events.rb
Fix tool permissions not being assigned to user after signup for non-membership orientation event
=> Fix tool permissions

data/updates/0005_sub_super_user.sql, models/permission.rb, models/user.rb, routes/admin/users.rb, views/admin/edit_user.erb, views/event_listing_table.erb, views/trainings.erb, views/workshop_listings.erb
This sub super user role will be able to do everything a super user can do except make/delete super users and sub super users
=> added new permission for sub super users

views/fixed.erb, views/fixed_no_toolbar.erb
Some people were getting errors related to conflicting encodings, this fixed their error
=> Added encoding to File.read

README.md, data/db_2024_10_03.sql, data/updates/0007_event_type_change.sql, views/fixed.erb
Changes:
- Added db_2024_10_03.sql, changing insert into event_types line 247
- Added 0007_event_type_change.sql, updating event_types table
Closes https://github.com/erohrs2/reservations/issues/2 Bad orientation event type value in database
=> 2 bad orientation event type value in database

routes/admin/users.rb, routes/new_members.rb, views/new_member_signup.erb
Changes:
- Removed vehicle inputs from new membership form for engineering garage
- Look up username based on email using directory.unl.edu for engineering garage
=> Engineering garage new membership form

views/admin/edit_user.erb, views/admin/users.erb, views/me.erb, views/new_member_signup.erb
Changes
- Added conditional statement to edit_user.erb, users.erb, me.erb, and new_member_signup.erb to only show vehicle information for certain SS ID's
Closes #21
Note: For new_member_signup.erb, changes are implemented but I am unable to get to the page and see the changes.
=> Completed Issue Disable parking erohrs2/reservations#21

Gemfile.lock, routes/events.rb, routes/new_members.rb, views/engineering_garage/email_templates/attended_orientation_email.erb, views/engineering_garage/email_templates/new_member_email.erb
Changes
- Removed references to event times and parking from flash for new members
- Removed event time reference from new member emails
- Removed parking and payment references from orientation emails
- Added Apple M3 to supported platforms
- Fixed a typo in flash for marked events
Closes [#143](https://github.com/cseseniordesign/GarageStudioManager/issues/143)
=> Completed Issue New Member Popup

routes/admin/maker_request.rb, scripts/email_expiring_maker_requests.rb, views/admin/home.erb, views/admin/maker_request_list.erb, views/navigation.erb
Changes:
- Added admin only maker request archive page (innovation studio only)
- Added new script for sending emails out when maker requests are about to expire (innovation studio only) 
CRON: 
- Run email_expiring_maker_requests script every 24 hours
=> Maker request archive

README.md, data/updates/0018_addtional_trainers.sql, models/event.rb, routes/admin/agenda.rb, routes/admin/events.rb, routes/events.rb, routes/export.rb, routes/home.rb, scripts/email_unconfirmed_trainers.rb, views/admin/agenda.erb, views/admin/new_event.erb, views/home.erb
Changes:
- Added multiple trainer columns to the DB
- Added new form sections to populate those columns
Database:
- 18 Add those new database columns
=> Two trainers

public/js/innovationstudio_new_member_vehicle.js, views/new_member_signup.erb
Form had some accessibility issues and bad logic for vehicle information. I also updated the design to not be so linear and one columned
=> Updated look and feel of form, and updated vehicle logic

routes/events.rb, routes/tours.rb
Actually checking to see if the email is an email before letting the person sign up for stuff
=> Validate email param before using it

views/admin/new_event.erb
Changes:
- Added JS script on the new event view for adding the require attribute on trainer input when training event is selected
=> Require trainer

routes/checkout.rb, views/engineering_garage/checkout_user.erb
Changes:
- Adds new "project interaction" feature which logs a check in or check out but does not change the project's status
- Added a few changes to project UI for visual appearance.
=> Project Interaction implemented
